add `author_url`
gustavwilliam/branding-bot pull request #7
Opened 2022-01-24 03:59 UTC by aphkyle

quick fix to /discord

2022-01-24 04:15 UTC, gustavwilliam requested changes
Thanks for the PR!

I tried doing `/discord embed title: hello description: there author: hello author_url: 0`. This raises: 
```py
disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In data.embeds.0.author.url: Scheme "0" is not supported. Scheme must be one of ('http', 'https').
```
Let's add some error handling for strange URLs.

2022-01-24 07:55 UTC, aphkyle commented
> Thanks for the PR!
> 
> I tried doing `/discord embed title: hello description: there author: hello author_url: 0`. This raises:
> 
> ```python
> disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
> In data.embeds.0.author.url: Scheme "0" is not supported. Scheme must be one of ('http', 'https').
> ```
> 
> Let's add some error handling for strange URLs.

Added error handler :D

2022-01-24 11:10 UTC, gustavwilliam requested changes

2022-01-24 11:10 UTC, gustavwilliam commented on bot/exts/discord/discord.py
> +from disnake import HTTPException, User
Why is this imported, since `disnake.HTTPException` is being used, instead of `HTTPException`?

2022-01-24 11:10 UTC, gustavwilliam commented on bot/exts/discord/discord.py
> +                    "Invalid URL responded."
```suggestion
                    "Invalid URL provided."
```
Maybe something like this? Or could we be more specific, like what attribute is creating this issue?

2022-01-24 11:10 UTC, gustavwilliam commented on bot/exts/discord/discord.py
> +                    "No valid embed could be generated form the given input."
```suggestion
                    "No valid embed could be generated from the given input."
```

2022-01-24 11:10 UTC, gustavwilliam commented on bot/exts/discord/discord.py
> +        """Error event of command `embed`"""
```suggestion
        """Error event handler for `embed` command."""
```
What do you think?

2022-01-24 11:13 UTC, aphkyle commented on bot/exts/discord/discord.py
> +from disnake import HTTPException, User
this was an accident, it is required to use `disnake.HTTPException` for the match case

2022-01-25 07:13 UTC, gustavwilliam approved these changes
Code-wise, LGTM. I'll just do some quick testing when I get home, but I don't really expect to encounter any issues with this.

2022-01-26 19:51 UTC, gustavwilliam commented
@aphkyle there was a bug or two in the code, but I (hopefully) fixed them while reviewing.

Thanks a lot for the PR 😄

2022-01-26 19:51 UTC, merged